version: '3'
services:
  postgres:
    image: postgres:11.7
    restart: always
    environment:
      POSTGRES_DB: coins
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432